version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db

  # For testing OpenFlow
  mininet:
    image: iwaseyusuke/mininet
    privileged: true
    network_mode: host
    tty: true

volumes:
  mongodb_data:
